### ISSUE TITLE
[BUG] curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by ct2034** [jatinchowdhury18/AnalogTapeModel#112]
When running `bash build_linux.sh` I get ... 

```
In file included from ../../JuceLibraryCode/include_juce_core.cpp:8:0:
../../../../modules/juce_core/juce_core.cpp:81:13: fatal error: curl/curl.h: No such file or directory
    #include <curl/curl.h>
             ^~~~~~~~~~~~~
compilation terminated.
```

I have got `libcurl4` installed.

**Comment by ct2034** [comment]
Seems to be solved by `sudo apt install libcurl4-gnutls-dev`

**Comment by jatinchowdhury18** [comment]
Hmm, I hadn't thought that `libcurl` was a necessary dependency. I should double-check that, thanks for letting me know.

In the meantime, yes, installing one of the `libcurl-*-dev` packages should give you the required headers.

Thanks!
Jatin

**Comment by magnetophon** [comment]
While packaging for NixOS, I found out there seem to be a few more dependencies:
```
    freetype
    libGL
    libXext
    python3
```

**Comment by jatinchowdhury18** [comment]
Ah, thanks for pointing that out, I'm adding some notes to the `Building.md` page to clarify this.

The `python` dependency is particularly annoying since I'm only using it to generate the .ttl files for the LV2 build. I've actually been working with the folks @DISTRHO to work out an easier way to build LV2 plugins with JUCE, that (among other things) doesn't depend on `python` (see [here](https://github.com/DISTRHO/JUCE/pull/13)). Eventually, when those changes go through, and I migrate this plugin to build with `CMake`, the `python` dependency should go away.

**Comment by magnetophon** [comment]
Great!
Does that mean there will be lv2 versions of more of your plugins?
I'm especially looking forward to Bad-Circuit-Modelling and DrumFixer!

**Comment by jatinchowdhury18** [comment]
Yes, the idea is that all my future plugins will support LV2 builds automatically! For past plugins, it will have to be a three-step process of:
1. Upgrading to JUCE6
2. Migrating from Projucer builds to CMake builds
3. Adding LV2 CMake target.

Since I'm not actively working on Bad-Circuit-Modelling, it may take me a while to get around to migrating those. However, I've been thinking about some upgrades for DrumFixer, so that could be happening sooner.
