### ISSUE TITLE
hack? How to install on Catalina

### ISSUE THREAD

**Issue by sveinbjornpalsson** [jatinchowdhury18/AnalogTapeModel#119]
The plugins would not load in Live, so I googled and found this guide:

https://www.osirisguitar.com/how-to-make-unsigned-vsts-work-in-macos-catalina/

It's fairly simple if you know how to do simple things in the terminal. 

I'm writing this to suggest that you offer up this information alongside the download.

**Comment by jatinchowdhury18** [comment]
Thanks for sharing this! Currently I have a link to [this article](https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave) in the user manual. I like this article since it doesn't require that users use the Terminal, but it looks like the link you shared might be safer and more robust... Do you have a preference for which article I should link to?

Either way, I'll be sure to add a link to the README as well, so hopefully it will be easier to find.

**Comment by jatinchowdhury18** [comment]
This issue is no longer relevant, since we now have signed and notarized installers available in the [nightly builds](https://chowdsp.com/nightly.html#tape)!
