### ISSUE TITLE
[BUG] Could not install in MacOS

### ISSUE THREAD

**Issue by alexaulbach** [jatinchowdhury18/AnalogTapeModel#129]
**Describe the bug**
Could not get the vst to run on Mac BigSur

**To Reproduce**
I downloaded the package and installed the .vst in the plugin-folder VST (and the app in the apps-folder). When I startup Reason DAW I got several mentions, that this is from unknown developer. Inside Reason it is shown as unknown developer and unknown type (none of  instrument, effect...). When I enable it and restart Reason nothing changes.

In the System Preferences this is also recognized: CHOWTapeModel.vst was blocked ... because it is from not identfied developer.
I tried to press the button "Open Anyway", but there is no effect.

When I use only the .vst3 plugin (installed into plugins/VST3) nothing happens.

**Expected behavior**
Should work after installation.

**Screenshots**
Could make them, if you really mean that would help. :)

**Desktop (please complete the following information):**
 - MacOS Big Sur
 - Reason 11

**Additional context**
I'm really new to this world of plugins. I would not wonder, if it was my fault. Then I'm sorry but would be glad, if got some help.
If not: My simplest estimated guess is, that this is because it has no plugin-type, Reason doesn't know what to do with it.

**Comment by jatinchowdhury18** [comment]
HI @alexaulbach,

Thanks for the detailed bug report. I have a few questions, but in general I would also suggest downloading the latest [development build](https://github.com/jatinchowdhury18/AnalogTapeModel/blob/master/Plugin/Bin/CHOWTapeModel-Mac-2.7.0.zip) which should be more compatible across different MacOSX versions.

- Are you able to run the .app file directly as a standalone application? It should work without needing to be run inside a DAW.
- Which plugin folder are you installing to? In the past, I've seen that some people need to install to `/Library/Audio/Plug-Ins/...`, while others need to install to `~/Library/Audio/Plug-Ins/...`.
- Are you able to load the Audio Unit version of the plugin? I don't think Reaper supports AUs, but you can use them in [GarageBand](https://support.apple.com/guide/garageband/use-audio-units-plug-ins-gbnde06a4e4d/10.4/mac/11.0).
- Finally, if the problem is related to the "unidentified developer" warnings, here's a couple links that can help:
  - https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave
  - https://www.osirisguitar.com/how-to-make-unsigned-vsts-work-in-macos-catalina/

Hope this information helps! Please let me know if you're still having issues.

Thanks,
Jatin

**Comment by alexaulbach** [comment]
Ok, I tested that. Now I have been able to run the standalone app. Wasn't possible with the previous version.

Currently ~/Library/Audio/Plug-Ins have no plugins installed, everthing is in /Library/Audio/Plug-Ins... I'll try, if later, if that changes something. But I doubt it.

With GarageBand the warning
 “CHOWTapeModel.component” can’t be opened because Apple cannot check it for malicious software.
pops up four times, then when choosing the plugin I have been asked the first time for the serial-nr. So that works well. :)

Still not working with Reason DAW, same problem as before. I will try your tips about installing "unidentified devs" tonight, but I won't wait with my response till tonight, so this is the provisory result. So far thanks! :)

**Comment by jatinchowdhury18** [comment]
Ah yeah, the fact that the standalone version wasn't working leads me to believe it was an OS compatibility issue. I think the articles on installing plugins from unidentified devs should be able to help get it working from there! Thanks for the update.

**Comment by alexaulbach** [comment]
I brought it to work following the links.  Thanks for all that good work!
