### ISSUE TITLE
For use with Pro Tools?

### ISSUE THREAD

**Issue by uhfreeman** [jatinchowdhury18/AnalogTapeModel#130]
I would love to be able to use this plugin in pro tools. Has anyone been able to figure out a way to do this?

Presently I have the component, vst, and vst3 versions installed and verified. It seems that  Pro Tools requires a .aaxplugin version to appear in the list of plugins?

I am using Mac OS Catalina (10.15.7) and Pro Tools 12.12

**Comment by jatinchowdhury18** [comment]
The short answer: we currently don't provide Pro Tools support for Chow Tape. This could be added in the future, but will require some significant effort.

The long answer:
Pro Tools uses their own proprietary plugin format, the aaxplugin that you had mentioned. I have made plugins for AAX before, but it's not particularly easy. Building an AAX plugin from source requires the AAX SDK, which I already have, however Pro Tools requires that plugins have been "signed" before it can load them. In order to sign your plugins, you must have an Avid Developer account (not sure if this requires a fee), and must register your product on their marketplace. This process is non-trivial, and I think they even make you take a "test" before making you a certified developer.

Another big question is licensing. Chow Tap is currently licensed under the GPLv3 and I'm not sure if this is compatible with Avid's requirements to be on their marketplace. Something I'll have to look into.

At the end of the day, I am hoping to add support for Pro Tools (and hopefully iOS as well). Unfortunately, I'm only working on these plugins part-time, and I often find it more gratifying to spend that time working on new DSP algorithms rather than fighting with different plugin formats, so it'll probably take me some time. Hopefully, in the next couple of months!

**Comment by jatinchowdhury18** [comment]
Hi there!

I was a little bit bored this morning, so I took some time to try making an AAX build for Mac. if you'd like to try it, the builds can be downloaded here: https://github.com/jatinchowdhury18/AnalogTapeModel/blob/aax/Plugin/Bin/CHOWTapeModel-Mac-2.7.1.zip.

Note that these builds are thoroughly un-tested, and may not work at all since I "signed" them with my Apple license, and not with an Avid certificate.

Thanks,
Jatin

**Comment by Bytor-dotcom** [comment]
Jatin great work. I loaded up the 2.7, and it open up on standalone, but I do not see it on my inserts?
I wonder if I have to drag to the plugins folder? Not sure has that is done either, but it does load up on the desktop. Would love to see it work in Pro Tools and give a shout out on the DUC forum on the great plugin.

**Comment by jatinchowdhury18** [comment]
Thanks @Bytor-dotcom,

Installing ChowTape through the "official" installer at the moment does not include an AAX build. If you'd like to try an AAX build, please download the zip file linked above, and move the ".aaxplugin" file into the Pro Tools plugin directory. As mentioned above, there is still a decent chance this build may not work because of signing issues.

I'm still thinking about adding official AAX support, though it'll probably take another month or two to work out fully. In the meantime, I know some folks have succesfully used ChowTape in Pro Tools using a "meta-plugin" like [DDMF's Metaplugin](https://ddmf.eu/metaplugin-chainer-vst-au-rtas-aax-wrapper/), [Blue Cat Audio's Patchwork](https://www.bluecataudio.com/Products/Product_PatchWork/), or [Kushview's Element](https://kushview.net/) (bonus points for being open-source :)).

Anyway, if you get a chance to try these test builds, definitely let me know how they work for you!

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
The latest nightly build now contains an AAX plugin: https://chowdsp.com/nightly.html. If anyone has the chance to test and report back, that would be super helpful!

**Comment by Bytor-dotcom** [comment]
Hi Jatin. Greatly appreciate your hard work. Will give it a spin after I'm
done with a session I'm working on. have a great weekend.

**Comment by jatinchowdhury18** [comment]
Working Pro Tools support has been confirmed with the nightly builds for both WIndows and Mac. Official AAX builds will be availble with the next release!

**Comment by Bytor-dotcom** [comment]
Awesome, thanks for the update! , have a great day.
