### ISSUE TITLE
random periodic clicks and sound exploding to the point of noise on ChowTapeModel and Hysteresis plugins

### ISSUE THREAD

**Issue by thejondoe** [jatinchowdhury18/AnalogTapeModel#15]
I don't know how to expand on the title information.after a certain point of playback,hysteresis begins to start introducing clicks that gradually progress to an explosion of dangerously loud noise.the same happens on ChowTapeModel but the reason for this is when you feed it too much input gain.

Info is:

OS:Windows 10
DAW's FL Studio 12 and Reaper 6

**Comment by jatinchowdhury18** [comment]
Hello!

Thanks for the bug report. I'll start doing some tests to see if I can figure out the root cause. A couple questions:

1.  Have you noticed this instability more for certain types of input? (i.e. high vs. low frequency, transient vs. steady state dynamics...)
2. When you refer to ("feeding it too much input gain"), are you referring to the input gain knob on the plugin, or adding more gain before the signal gets to the plugin? I've tested with signal at unity gain going into the plugin with the full range of settings for the input knob, but I've never tried with larger than unity gain going into the plugin.
3. What amount of oversampling are you using? Does the behavior get better or worse with more oversampling?

Any extra information would be great! I'll keep you posted how my testing goes as well. Thanks!

**Comment by thejondoe** [comment]
Hi Jatin

Apologies i didn't elaborate much on the above points.i will address them
now

1.no the instability is not signal dependent.it will occur eventually
regardless of the signal.i've tried drums,synths,things with and without
low end and it happens irregardless of all these examples

2.i meant using external gain,but not much beyond what is available from
the plugin itself.around an extra 5dB

3.oversampling does not seem to improve the issue.in ChowTapeModel at
least.there is no oversampling option in Hysteresis,but i oversampled
Hysteresis in Metaplugin by 2 and 4x the samplerate and the same clicks
that develop to become "a dangerous explosion of noise"occurs eventually.at
first i thought it was DC related so i used DC blocking filters,but it
didn't make much of a difference.i have a plugin called ICE9 on my master
that automutes the audio beyond a certain point,so i haven't been a victim
of it yet,but it gets pretty up there(the noise) :)


Regards

Jon

**Comment by jatinchowdhury18** [comment]
Hi Jon,

Okay, thanks for the extra information. As I mentioned in #14, I've been starting to play around with adding pre/post EQ filters, and these seem to fix the problem of blow-ups in the tape machine (most likely due to the way the hysteresis processor handles content at different frequencies, I'm still working through the math). Still need to figure out a more general solution for the Hysteresis processor itself, but I'll keep you posted as soon as I have something ready for you to try!

Thanks,
Jatin

**Comment by thejondoe** [comment]
Look forward to it Jatin

Hysteresis is very reminiscent of real transformers for me.the way it soaks
up the sound.most transformer plugins i have played with thus far bar one
(Sknote's AnyTesla but it has its shortfalls too)sound absolutely nothing
like transformers and are glorified static  waveshapers in my opinion
regardless of whatever supposed circuit modelling is going on (a sound i am
all too sick of hearing in plugins)i read that you was in the process of
modelling some poorly performing op-amps as well.if you could keep me
updated on that i'd love to check those out too or any of your developments
into the quirks of nonlinearties that are so often missing from the usual
suspects of plugins

Kind Regards

Jon

**Comment by jatinchowdhury18** [comment]
Hi Jon!

I've done some more testing and have found that some of the pre/post EQ curves do help with the stability issues you noted. Still working to embed a solution in the hysteresis processor itself. Currently fixing some noise issues with the pre/post EQ, but hopefully that will be ready soon.

Glad you're enjoying the model! I have been working on some bad op-amps as part of one of my other projects. They're still very much in progress, but here's some build for that if you'd like to try them out: https://github.com/jatinchowdhury18/Bad-Circuit-Modelling/tree/master/Bin.

Thanks,
Jatin

**Comment by thejondoe** [comment]
Hi Jatin

Just finally got round to playing around with SallenKey and Diode
Clipper..wow lol.Diode Clipper especially surprised me.it sounds pretty
amazing.i was just wondering is possible to make the temperature driven
randomness more subtle?it seems to go from 1 to 100 at the slightest change
in temperature.it sounds authentic to me,but it would be nice if there was
a little more leeway in the result.is it possible you will also be working
on a broken tube model in the future,possibly some other solid state
components like opamp clipping,JFET's etc?i am really just curious to hear
your take on anything really.i have enjoyed everything very much so far

Regards

Jon

**Comment by jatinchowdhury18** [comment]
Hi Jon,

Glad you're enjoying them! I can definitely tweak that knob to make that a little bit smoother.

Currently, I'm working on capacitor leakage, and then hoping to get into more nonlinear elements like you described. Op-amp clipping has been covered pretty well by some other DSP folks (I particularly like [this paper](http://dafx2019.bcu.ac.uk/papers/DAFx2019_paper_6.pdf)) but could definitely be worthwhile to include in these models. Broken tubes would be fantastic, a colleague and I have discussed potentially doing some research on that, though it may take a little bit longer given how complex tubes can be. JFETs, BJTs, etc, would be great to be modelling as well. It'll definitely be dependent on what I have time for, but I'm definitely excited to keep pushing on this!

Thanks,
Jatin
