### ISSUE TITLE
(Noob alert) had some problem compiling from source

### ISSUE THREAD

**Issue by Yandrut** [jatinchowdhury18/AnalogTapeModel#163]
Been working on Linux Mint
   ~/AnalogTapeModel/Plugin$ cmake -Bbuild
-- Checking for module 'libcurl'
--   No package 'libcurl' found
-- Checking for modules 'webkit2gtk-4.0;gtk+-x11-3.0'
--   No package 'webkit2gtk-4.0' found
--   No package 'gtk+-x11-3.0' found
-- Checking for module 'freetype2'
--   No package 'freetype2' found
-- Configuring juceaide
-- Building juceaide
CMake Error at modules/DISTRHO-JUCE/extras/Build/juceaide/CMakeLists.txt:86 (message):
  Failed to build juceaide

  [ 12%] Building CXX object
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_graphics/juce_graphics.cpp.o

  
  /home/digital/AnalogTapeModel/Plugin/modules/DISTRHO-JUCE/modules/juce_graphics/juce_graphics.cpp:88:12:
  fatal error: ft2build.h: No such file or directory

     88 |   #include <ft2build.h>
        |            ^~~~~~~~~~~~

  compilation terminated.

  make[2]: *** [extras/Build/juceaide/CMakeFiles/juceaide.dir/build.make:102:
  extras/Build/juceaide/CMakeFiles/juceaide.dir/__/__/__/modules/juce_graphics/juce_graphics.cpp.o]
  Error 1

  make[1]: *** [CMakeFiles/Makefile2:133:
  extras/Build/juceaide/CMakeFiles/juceaide.dir/all] Error 2

  make: *** [Makefile:130: all] Error 2

-- Configuring incomplete, errors occurred!
See also "/home/digital/AnalogTapeModel/Plugin/build/CMakeFiles/CMakeOutput.log".
See also "/home/digital/AnalogTapeModel/Plugin/build/CMakeFiles/CMakeError.log".

I guess this is an issue with dependencies 

Depending on your Linux distribution, you may also need to install:

    freetype
    libGL
    libXext
    libcurl
and I guess versions of these packages in my system are different, but compiler searches for the ones it needs, but not sure about that

Following packages in my system 'freetype2-doc' 'libgl1' and a lot of stuff that it depends on, 'libxext-dev' or 'libxext6' , 'libcurl4' , 'libwebkit2gtk-4.0-37'

and gtk+-x11-3.0 is not there, i guess

how can i make this work?

**Comment by jatinchowdhury18** [comment]
Hi there!

Sorry to hear that you're having compilation issues. It looks like the main issue is that CMake isn't able to find `freetype2` in your system. Potentially, there could be a problem with `webkit` and `gtk` as well, since CMake couldn't find those either. [This page](https://github.com/juce-framework/JUCE/blob/master/docs/Linux%20Dependencies.md) gives some pretty good information about the Linux dependencies needed to compile a JUCE project like this one. I think installing (or re-installing) some or all of these dependencies would likely fix the issue.

Another option, if you just want to use the plugin and don't really care about compiling from source, is to download the Linux installer that I've recently been working on. There still may be some bugs to work out with this process, so definitely let me know if you run into issues. The installer can be downloaded [here](https://chowdsp.com/nightly.html).

Thanks,
Jatin

**Comment by Yandrut** [comment]
@jatinchowdhury18 thank you so much for a reply :) 
It was as easy as installing few packages in terminal. It's the case with me getting lost with packages and libraries and stuff. Compiled it works like charm. Definitely will be testing it out top to bottom. Can I support your development financially? 
What do you think about internationalisating the UI? It definitely would be a good feature, I could help translating to a few languages

**Comment by jatinchowdhury18** [comment]
Great, glad to hear that it's working! For financial support, we have a [Patreon](https://www.patreon.com/chowdsp) page.

I imagine having translated version of the plugin should be possible, I'd just need to figure out how to dynamically change the UI configuration on the fly. I can let you know when I've got that ready (I don't have a time-estimate on that quite yet).

**Comment by Yandrut** [comment]
@jatinchowdhury18 it'd be a nice feature to make it more accessible, but I think if people can download it In English they surely will understand what UI is all about. Let me know anyway if you'll think its worth the effort 👍
