### ISSUE TITLE
blank update screen on some PCs

### ISSUE THREAD

**Issue by wolfmusictech** [jatinchowdhury18/AnalogTapeModel#200]
Hello, 
Firstly thank you for your excellent freeware plugins!
We have just rebuilt the PCs in our music classroom and on some PCs the update screen for ChowTapeModel is blank. Other machines it shows fine and you can either click yes or no.
The screens that are blank you can still select presets and this will affect the sound but you cannot adjust any of the parameters. 
![Screenshot (2)](https://user-images.githubusercontent.com/85342697/120791056-9d677200-c52b-11eb-9ae3-9f0bf2d6d005.png)
I have tried updating both this plugin and also the ChowMatrix. The update works when running the .exe installer but it will not work when copying the .vst3 file directly to another PC. I have tried clearing the cache and rescanning VSTs and i have tried restarting the PC.
We like to be able to copy the plugins directly so it is easy to rebuild the room rather than having to run lots of installers on lots of PCs one after another.
Some plugins we use have files that also need copying to ProgramData, but I couldn't see anything there for ChowDSP and the last versions worked great only copying the .vst3 file.
Any help you can offer would be greatly appreciated :-)
Many thanks,
Stephen

**Comment by jatinchowdhury18** [comment]
Thanks for reaching out, sorry that you're running into this issue! Definitely makes sense that you would want to avoid having to re-run the installer a bunch of times. I'm assuming that all of the PCs in question are Windows machines?

What's interesting is that the only thing the installer does is copy the plugin file into the plugin folder, much as you're doing. Here's a couple things to try:
- Delete the application data folder (for me it's at `C:\Users\jatin\AppData\Roaming\ChowdhuryDSP`). The plugin will re-generate everything in that folder the next time is run.
- Try copying the .vst3 binary file instead of the .vst3 directory (`\path\to\plugin\folder\CHOWTapeModel.vst3\Contents\x86_64-win\CHOWTapeModel.vst3`)
- If all else fails, it may be possible to automate downloading and running the installer on multiple computers using a bash script or something similar for Windows. I'm happy to help with this if needed.
