### ISSUE TITLE
[Discussion] Should Oversampling be saved in presets?

### ISSUE THREAD

**Issue by not-holar** [jatinchowdhury18/AnalogTapeModel#201]
Currently oversampling is saved in presets, but i'm not sure if it should, typically it's something you would set depending on where you use it and how powerful your machine is, not really on the settings of a preset (perhaps it matters if your preset uses a lot of gain for overdrive).  
  
In a hypothetical situation with how it works right now, let's say you wanted to add some tape flavour when mastering, naturally, the first thing you'd do is set the highest oversampling setting, you'd change some settings around, decide you'd want to use some preset instead, start scrolling through them. Your oversampling setting would get overwritten with the (typically low) one from a preset, potentially doing so without you noticing and possibly introducing some aliasing to your master. This could be made even worse when #198 is implemented, as you wouldn't hear the problem right away.  
  
I'm interested to hear what other people think of this.

**Comment by jatinchowdhury18** [comment]
This is a good point, and something that I had thought about when originally implementing the oversampling options. The situation that you give is a good example of the problems that could arise with the current implementation. However, as a counter-example, I have a couple of presets that I typically use for vocals where I like to have more oversampling, so if I'm scrolling through presets, I would prefer for those to stay with the oversampling rate saved in the preset so that when I go to use that preset on a vocal track, I wouldn't need to also set the adjust the oversampling rate to the setting that I use with that preset.

I would definitely also love to hear more opinions on this idea.

**Comment by not-holar** [comment]
As an idea, preset oversampling could act as a minimum, so the instance would follow the presets' settings as long as they're not lower than the one manually set by the user.

**Comment by jatinchowdhury18** [comment]
That's good idea... the only issue I could foresee is that the behaviour may not be immediately obvious to the user, which could lead to some confusion. I'll try to ask around today on a couple of forums and hear some more opinions.

**Comment by jatinchowdhury18** [comment]
Apologies, I've been super busy the last week or so. I'll get back on this today.

**Comment by jatinchowdhury18** [comment]
Okay, so after asking around, I think the general consensus is that the oversampling factor should be determined by the user and not affected by changing presets. Someone mentioned that there could be an option to allow presets to override the user's selected oversampling behaviour, but I worry this would be more confusing than useful in the general case.

Anyway, I'll get started on writing the code for this change this weekend.

**Comment by jatinchowdhury18** [comment]
This change is now implemented, and can be tried with the [NIghtly Builds](https://chowdsp.com/nightly.html#tape). Thanks @not-holar for the suggestion!

Thanks,
Jatin
