### ISSUE TITLE
DAW crash - Preset folder

### ISSUE THREAD

**Issue by greytomorrow** [jatinchowdhury18/AnalogTapeModel#203]
When accessing either "Go to Preset folder..." or "Choose Preset folder..." from the UI drop-down menu, the entire DAW (in my case, GarageBand) crashes.

**Expected behavior**
Either Finder should open the Preset folder ("Go to Preset folder") or a dialog should open to select a Preset folder location ("Choose Preset folder...").

 - OS: macOS 10.13.6
 - GarageBand 10.3.2
 - Chow Tape Model v2.8.0, AU
 
**Attachments**
[crash_log.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/6670570/crash_log.zip)

Thank you.

**Comment by jatinchowdhury18** [comment]
Hi @greytomorrow,

Thanks for reporting this, and for including the crash reports, that's super useful for debugging.

GarageBand is a bit of a special case since it uses a "sandbox" which are used to isolate the plugin from the rest of the computer's file system. So when the preset menu attempts to access the file system through those menu options, that's what's causing the crash. For confirmation, this line appears in the crash reports:
```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSObjectNotAvailableException', reason: 'SaveOpenPanel_e9b9b38b3517282 is not a supported subclass for sandboxing'
MAManchester | 94d3b910e514cb711d268bc5d953046c3bb629e70a5564a403b3bde53d2a75b7 | b5a3763eeeb9cd03d024bdb84b9d5975b70318b3 | 2018-12-03_14:10:56
```

A couple things worth checking:
- Make sure that GarageBand has the correct permissions for accessing the file system (see [here](https://forum.juce.com/t/plug-in-cant-access-external-resource-files-on-osx/42312/12)).
- Try opening the Standalone version of ChowTape and going to the preset folder from there. If the crash still happens with the Standalone version, the we know that issue is something deeper than the GarageBand sandbox.

In the meantime, I'll do a it more reading about the sandboxing process, and see if maybe there's more permissions that I need to enable in the plugin or installer to get it working correctly.

Thanks,
Jatin

**Comment by greytomorrow** [comment]
>  -  Try opening the Standalone version of ChowTape and going to the preset folder from there. If the crash still happens with the Standalone version, the we know that issue is something deeper than the GarageBand sandbox.

The issue does not exist with the standalone version. Standalone displays expected behaviour.

I realize macOS 10.13 is already three versions behind the current OS (GarageBand doesn't appear in the Privacy settings in this version), not to mention the recent Mac architecture change. The plugin otherwise works perfectly. I'd be curious though if this issue occurs on later OS/GarageBand versions than my own.

Thanks, @jatinchowdhury18, for looking into this issue and especially for your great plugin.

**Comment by jatinchowdhury18** [comment]
> The issue does not exist with the standalone version. Standalone displays expected behaviour.

Ah okay, thanks for letting me know! I guess I should have also mentioned that I wasn't able to re-create the crash in GarageBand on my local computer (macOS 10.15.6, GarageBand 10.3.4). I'll keep investigating, and see what else I can learn.

Thanks,
Jatin

**Comment by jatinchowdhury18** [comment]
Wanted to check in to see if this issue was still occurring, particularly with the [latest nightly builds](http://chowdsp.com/nightly.html).

i actually ran into a similar issue with needing permissions for an app that wasn't showing up in the privacy settings, and what fixed it for me there was running the application from the command line. In this case it should be something like: `/Applications/GarageBand.app/Contents/MacOS/GarageBand`. If that does actually fix the crash, then I'm honestly not sure if there's anything I could change in my implementation that would fix it :(.

**Comment by greytomorrow** [comment]
Ciao, Chow... 🤣

This morning after seeing your reply, I tested the same CTM 2.80 in GarageBand 10.3.2 *and* Tracktion Waveform Free 11.5.18 (Built: 12 July 2021).

- In GarageBand, obviously nothing changed (crash). Apologies, but I didn't install the nightly build. Invoking GarageBand from the command line changes nothing...
```
24  libdyld.dylib                       0x00007fff6cd7b015 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```
[GarageBand_2021-09-06-111525.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/7114893/GarageBand_2021-09-06-111525.zip)


- In Waveform, *no crash*. "Go to Preset Folder" and "Choose Preset Folder" work perfectly, both open a Finder window.

Draw your own conclusions. Thanks for your interest but as far I as I'm concerned, you can close this issue.

**Comment by jatinchowdhury18** [comment]
Ciao!

Glad to hear that it is working correctly in Waveform... definitely sounds like something specific related to that version of GarageBand (I haven't been able to re-create the crash in version 10.3.4).

Graze mille,
Jatin
