### ISSUE TITLE
[BUG] Cannot build on NixOS

### ISSUE THREAD

**Issue by magnetophon** [jatinchowdhury18/AnalogTapeModel#215]
**Describe the bug**
The output is too long for an issue comment.
https://gist.github.com/magnetophon/a315559adab71202c1b0f529f9fc2945
I hope you can spot the issue!

Thanks!

**Comment by jatinchowdhury18** [comment]
Hi @magnetophon, I was actually thinking about #164 the other day (possibly a duplicate?), and was wondering whether or not we had actually solved it (I guess not).

Anyway, looking at the latest build logs in your above link, I think the problem is something to do with this message on [line 140](https://gist.github.com/magnetophon/a315559adab71202c1b0f529f9fc2945#file-buildoutput_chowtapemodel-txt-L140):
```bash
[ 47%] Linking CXX static library libjuce_plugin_modules.a
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ar: CMakeFiles/juce_plugin_modules.dir/DISTRHO-JUCE/modules/juce_audio_utils/juce_audio_utils.cpp.o: plugin needed to handle lto object
/nix/store/v8imx1nvyz0hgvx9cbcmh6gp4ngw3ffj-binutils-2.35.1/bin/ranlib: libjuce_plugin_modules.a(juce_audio_utils.cpp.o): plugin needed to handle lto object
```
From looking at [this Reddit post](https://www.reddit.com/r/Gentoo/comments/6b1dlc/plugin_needed_to_handle_lto_object_and_correct/), one idea is to try using the lto tools from gcc instead of binutils. So maybe try setting these environment variables before building:
```bash
AR="/nix/store/4xs1xyj8728yvh9y5v6ji819kwgfy2fv-gcc-wrapper-10.3.0/bin/gcc-ar"
NM="/nix/store/4xs1xyj8728yvh9y5v6ji819kwgfy2fv-gcc-wrapper-10.3.0/bin/gcc-nm"
RANLIB="/nix/store/4xs1xyj8728yvh9y5v6ji819kwgfy2fv-gcc-wrapper-10.3.0/bin/gcc-ranlib:
```

**Comment by magnetophon** [comment]
Yes, that does the trick!

Thanks!
