### ISSUE TITLE
Doesn't build on linux aarch64

### ISSUE THREAD

**Issue by Bleuzen** [jatinchowdhury18/AnalogTapeModel#236]
Hi, I currently try to build this plugin as a flatpak and on flathub:
https://github.com/flathub/flathub/pull/2681

Flathub usually builds for x86_64 and aarch64. The problem is that the aarch64 build fails.

According to this comment:
https://github.com/flathub/flathub/pull/2681#issuecomment-996084644
> vvtanh is missing and from what I gather it's because they assume aarch64 == Apple.

You can find the currently latest build log here:
https://flathub.org/builds/api/v2/logs/2903750/raw

**Comment by jatinchowdhury18** [comment]
Hi @Bluezen, thanks for reporting this, and for the detailed report! The good news is that it looks like that error was present in some obsolete code leftover from an old implementation of that class. I just pushed a fix to the `develop` branch that removes the obsolete code. Definitely let me know if that works for you!

**Comment by hfiguiere** [comment]
I have two different patches. One being in `chowdsp_utils`. They are untested at the moment (ie things build).

**Comment by jatinchowdhury18** [comment]
@hfiguiere For the PR in this repo, I believe I've already fixed that problem on the `develop` branch. Would it be possible to test from there?

For the PR in `chowdsp_utils`, would it be possible to share the error messages related to that change? My understanding was that `aarch64` should support SIMD instructions for double-precision floats. Otherwise, I might need to provide some different `#if / #else` fallbacks there.

Thanks!

**Comment by Bleuzen** [comment]
@jatinchowdhury18 
> I believe I've already fixed that problem on the develop branch. Would it be possible to test from there?

Did that, build failed, log:
https://flathub.org/builds/api/v2/logs/2908486/raw

**Comment by hfiguiere** [comment]
This is the same error that Chowdhury-DSP/chowdsp_utils#98 addresses.
The patch itself is still valid (one-liner), if that the right solution.

**Comment by jatinchowdhury18** [comment]
Gotcha, thanks for including the build log again. It seems like the first issue is fixed, so that's definitely a good sign! For the remaining issue, I don't think the one-line fix is correct, since that will "turn off" most of the double-precision SIMD methods on all ARM platforms, which would definitely have a big performance hit.

I was able to investigate a bit further, and I think I've found the problem: `xsimd::isnan` returns a SIMD register of booleans, which I try to cast as a batch of doubles in my wrapper:
```cpp
/** SIMD implementation of std::isnan */
template <typename T>
inline typename juce::dsp::SIMDRegister<T>::vMaskType isnanSIMD (juce::dsp::SIMDRegister<T> x)
{
    using Vec = juce::dsp::SIMDRegister<T>;
    return Vec::notEqual ((Vec) xsimd::isnan ((x_type<T>) x.value), (Vec) 0);
}
```
What really confuses me is that the compiler seems to allow this cast with SSE SIMD instructions, and when compiling for ARM with Clang... Anyway, I'll dig into it and hopefully can have it fixed soon!

**Comment by hfiguiere** [comment]
> What really confuses me is that the compiler seems to allow this cast with SSE SIMD instructions, and when compiling for ARM with Clang... Anyway, I'll dig into it and hopefully can have it fixed soon!

Does it throw warnings? Sometime warnings are actual errors. (I saw the x86_64 had a lot)

And yes I was building with gcc 10.2 or 11.2 which are the default here, be it plain Debian aarch64 or Freedesktop-SDK (the runtime for Flatpak)

**Comment by jatinchowdhury18** [comment]
Yeah, I haven't seen any warnings about that specific section of code either. Maybe I need to adjust my warning flags to be more strict... Anyway, I have an attempted fix now on the [`isnan-fix`](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/isnan-fix) branch, if you want to give it a try.

**Comment by Bleuzen** [comment]
@jatinchowdhury18 now it fails on x86_64:
https://flathub.org/builds/api/v2/logs/2909127/raw

**Comment by jatinchowdhury18** [comment]
Ah, the plot thickens... it seems like `xsimd::isnan` returns a batch of unsigned ints on ARM NEON, but when using SSE SIMD instructions it returns a batch of doubles. This explains why I previously wasn't getting errors or warnings when compiling for x86_64. I've pushed a new fix to the `isnan-fix` branch if you want to try that out.

**Comment by Bleuzen** [comment]
@jatinchowdhury18 
With the new fix, build works now on both x86_64 and aarch64. Thank you :)

**Comment by jatinchowdhury18** [comment]
Great! I'll take care of getting all the fixes merged down to `develop` and then `master`. Thanks for being patient and helping to get everything fixed!
