### ISSUE TITLE
[FEATURE] Allow to overwrite build formats

### ISSUE THREAD

**Issue by Bleuzen** [jatinchowdhury18/AnalogTapeModel#238]
**Is your feature request related to a problem? Please describe.**

I want to build only the VST3 and LV2 plugin, not interested in anything else. Can I somehow overwrite the `JUCE_FORMATS` var to only build those two?

**Describe the solution you'd like**

Could be an environment variable or cmake configure option to overwrite the formats to build.

**Additional context**

I try to package this plugin on flathub (linux software repository/app store). There, a package can only either be a desktop application (the standalone) or an extension (for example audio plugin). It is not possible to put both into one package. So for the plugin package, I only want to build VST3 and LV2 and maybe if a separate desktop package will be made later, only Standalone should be built. For that an option to force set build targets / formats would help.

**Comment by jatinchowdhury18** [comment]
So with the current CMake setup, when you run the CMake "configure" step (`cmake -Bbuild ...`), the build system will automatically set up a build target for each plugin format that is available on the that platform. I think I would like to leave this behaviour as-is.

However, when _building_ with CMake, it is possible to specify a single target that you would like to build. For example, to only build the VST3 and LV2 plugins:
```bash
cmake --build build --target CHOWTapeModel_VST3 ...
cmake --build build --target CHOWTapeModel_LV2 ...
```
With most build systems, the second command should run much faster than the first, since any shared dependencies will already have been built.

Or if you only want the standalone plugin:
```bash
cmake --build build --target CHOWTapeModel_Standalone ...
```
Would specifying the desired targets in the build command(s) work for your use case? Or is there a particular reason you would need to include/exclude certain targets at configuration time?

**Comment by Bleuzen** [comment]
Thanks, got it working now!

At first it didn't work. Took me some time but turns out that this was caused by flatpak automatically running make install and this leads to all targets being built. With that disabled, the targets work now (even with ninja instead of cmake) :)
