### ISSUE TITLE
[FEATURE] Collection repository

### ISSUE THREAD

**Issue by Bleuzen** [jatinchowdhury18/AnalogTapeModel#239]
Hi, this is not specific to this plugin but didn't know where to ask.

Some plugin developers who have multiple plugins put them together into a collection. This makes it easier to package all the plugins as a bundle / one package.
So there could be one repository called something like "Chow Plugins", which contains all of your plugins as submodules.
As an example, take a look at x42-plugins:
https://github.com/x42/x42-plugins

Is there something like this planned?

**Comment by jatinchowdhury18** [comment]
Hi!

Having a "collection" repo is not really something I had thought about, but I definitely see the benefits that it could have from a "packaging" standpoint.

Currently, there is a ["releases"](https://github.com/Chowdhury-DSP/releases) repo, which I use for making nightly builds of each plugin. The repository only contains a GitHub Actions pipeline, build scripts for each plugin, and a little bit of metadata for each plugin... I wonder if that process could be simplified by using submodules instead. Then from there maybe we could add extra scripts for building/packaging multiple plugins at a time.

Anyway, this is a cool idea... I'll have to think about it a little more, and I'm definitely open to suggestions for how this sort of thing could be structured. I'd also love suggestions for renaming the "releases" repo, since it may now be used for more than just running nightly builds. For now, I'll also move this issue into that repo.

Thanks,
Jatin
