### ISSUE TITLE
[BUG] Performance issues with v2.10.0

### ISSUE THREAD

**Issue by muziker** [jatinchowdhury18/AnalogTapeModel#253]
**Describe the bug**
Using two of these inline causes immediate XRUNS. Also if the input is too hot, something internally gets glitchy. The DAW host starts to glitch out and the host timing jittering like there's large CPU spikes even though there is none. Probably within the chain of audio, there needs to be a way of limiting spikes that mess up the saturation/degrade algorithm. Or possibly denormals.  

**To Reproduce**
1. Add two of the plugins inline
2. Immediate XRUNs

**Expected behavior**
Silky tape emulation

**Desktop (please complete the following information):**
- ubuntu 20.04
- reaper

**Additional context**
Could this be some kind of shared buffering issue? How can this be debugged, since the plugin runs within the reaper process

**Comment by muziker** [comment]
It's somewhere in the Tape/Comp/Tone section

**Comment by jatinchowdhury18** [comment]
Thanks for reporting this issue! I'd imagine the XRUNS are coming from the "Tape" processing section since that's the computationally complex part of the DSP. A couple of follow-up questions:
- Was this running on an Intel or ARM CPU? I've tested the plugin on the Mac M1 ARM CPUs, but I haven't tested on any ARM devices running Linux. Some older ARM CPUs may not support some of the SIMD intrinsics that are relied on by the tape processing.
- Were you using the provided binaries from the releases or nightly builds page, or were you building from source? If building from source, you may want to add `-DCMAKE_BUILD_TYPE=Release` to the CMake configure command. I thought I had added this flag to the building instructions, but it looks like I had missed it.
- It is possible to debug the plugin in a host, by attaching the debugger to the host process. I haven't tried doing this on Linux, but it should be possible. An easier approach could be to build the standalone plugin target, and debug that.

**Comment by muziker** [comment]
It's on an intel, but good to know about the arm intrinsics. I specified cmake --config Release, thinking it was the same as -DCMAKE_BUILD_TYPE=Release. But now that it's rebuild, it's working a lot better. I'm not sure about hooking into the host process with gdb. There's quite a number of reaper sub processes. Too bad there isn't like somekind of tutorial on debugging multi threaded programs. 

But thanks for the great plugin btw !

**Comment by jatinchowdhury18** [comment]
Glad to hear the rebuild is working better! My understanding is that the `CMAKE_BUILD_TYPE` is required when the CMake generator is Makefile-based. If the CMake generator is an IDE (e.g. Xcode or Visual Studio), then just using the `--config` argument during the build step is good enough.
