### ISSUE TITLE
[FEATURE] Multichannel processing

### ISSUE THREAD

**Issue by jeanloupPecquais** [jatinchowdhury18/AnalogTapeModel#254]
Hello !

Is there any chance to get a multi-channel version of the ChowTape model? With immersive audio becoming more and more present, there is a real lack of saturation plug-in that can handle more than stereo. 16 in / 16 out would be perfect for working up to 3rd order ambisonic or to handle some Dolby Atmos beds (7.1.2).

Hope it makes sense, thank you !

**Comment by jatinchowdhury18** [comment]
Hi! Yeah, having multi-channel support would be very cool. Currently there are a few roadblocks that will have to be figured out:

The main one is that the tape hysteresis algorithm is parallelized across the number of channels using SIMD registers. Since the that processing is double-precision, and most SIMD instruction sets support SIMD registers that can hold two double-precision values, it works out just right for stereo input, and mono input can be dealt with trivially as well. For more than two channels, we would need to break up the input buffer into sets of two (or fewer) channels, and process each set one-by-one.

Beyond that, there are a few parts of the plugin (e.g. mid-side mode, azimuth), that expect a stereo input, so those parameters would either need to be removed when the plugin is being used in a multi-channel context, or the algorithm would need to be adapted to each specific channel configuration.

So I think it should be possible, but it will need some thought and time. I'll see if I can make some time to investigate a bit further in the next couple weeks.

**Comment by jatinchowdhury18** [comment]
Multi-channel support has now been added with #255! The current implementation is intended to support any channel configuration, so long as the number of input and output channels are the same.

So far I've been doing some testing mostly in 5.1 and 7.1, but as I don't typically use these channel layouts, I'm sure there are edge cases that my testing has missed. If @jeanloupPecquais or anyone else has a little bit of time to test, either with the [nightly builds](https://chowdsp.com/nightly.html#tape), or building from the `develop` branch, that would be greatly appreciated!

**Comment by jpecquais** [comment]
Hello !
Thank you very much for this ! I tested it this morning on a 3rd order ambisonic bus, it seems to work fine ! I'll let you know if I encounter any issue.

**Comment by jatinchowdhury18** [comment]
Glad to hear it's working for you! Thanks for testing 👍
