### ISSUE TITLE
32 bit VST build? 

### ISSUE THREAD

**Issue by Boscop** [jatinchowdhury18/AnalogTapeModel#31]
I'm still using only 32 bit VSTs in a 32 bit host (because most VSTs I'm used to using are only available for 32 bit).
Can you please add a dll compiled for 32 bit VST hosts to the release assets? :)

**Comment by jatinchowdhury18** [comment]
Sure thing! Could you let me know how this works for you?
[CHOWTape-Win32-2.2.0.zip](https://github.com/jatinchowdhury18/AnalogTapeModel/files/4606475/CHOWTape-Win32-2.2.0.zip)

**Comment by Boscop** [comment]
@jatinchowdhury18 Thanks so much! It works, it sounds great!
I tested it in Reaper at 44.1 kHz.
But I noticed a few issues: When the flutter knob crosses between 0 (off) and nonzero (on), there are audible clicks.
Sometimes I get huge volume spikes so that Reaper automutes the track (to avoid damage to ear/speakers).
E.g. with these settings if I play around with the gap slider:

![image](https://user-images.githubusercontent.com/535593/81641501-6ce4ff80-9421-11ea-9dbf-e84218167d8e.png)

(This is a screenshot of when it happened, as you can see the signal display shows nothing.)

And then I have to wait several seconds (like 7s) until the level is back to normal (until Reaper lets me unmute the track again).

But overall it sounds great, I'm really looking forward to using this :)

**Comment by jatinchowdhury18** [comment]
Hi @Boscop,

Great that the 32-bit is working on your system! I'll start posting zip files like that with future releases.

Thanks for the detailed reports on the other bugs you experienced. The click on the flutter knob should be a fairly simple fix, I can take a look at that today.

The larger volume spikes are a problem that's been reported a few times. I think the way to solve that will be to use the alpha transform rather than the bilinear transform for discretizing the hysteresis nonlinearity. This will be a bit moe involved, but I'll keep you posted as this progresses.

Thanks,
Jatin

**Comment by Boscop** [comment]
Thanks a lot, it's nice to have a 32 bit version as well :)
I'll update regularly and let you know if I find any other issues.

**Comment by Boscop** [comment]
@jatinchowdhury18 Btw, I think it would make sense to have a second set of 2 knobs for wow ("depth" and "rate" just like for flutter). 
I'm not an expert on tape, but AFAIK both wow and flutter can occur at the same time (flutter being fast and wow being slow), right?

**Comment by jatinchowdhury18** [comment]
Hi @Boscop, moving this to a separate thread #33.
