### ISSUE TITLE
[BUG] Problem in linux mint 20.

### ISSUE THREAD

**Issue by TheGuyWhoo** [jatinchowdhury18/AnalogTapeModel#312]
In reaper. tapemodel v2.11.4. Lv2 immediately goes offline, other formats don't even scan.

swell: dlopen() failed: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/lv2/CHOWTapeModel.lv2/CHOWTapeModel.so)

**Comment by TheGuyWhoo** [comment]
I recall this same issue was present in multitool vst.

**Comment by jatinchowdhury18** [comment]
Hi, thanks for the bug report!

This does seem similar to https://github.com/Chowdhury-DSP/ChowMultiTool/issues/25. We were able to fix that one by down-grading the build machine to [Ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md). With ChowTape, the latest release was built on the same machine, so I doubt it's the _exact_ same issue. Since the changes made for MultiTool, the only change we've made to the Linux machine has been to install GCC-11 on the machine, however, for building ChowTape, we're still using GCC version 9.4.0.

I wonder if the steps provided [on this thread](https://www.reddit.com/r/linuxmint/comments/p0yshr/having_troubles_with_libstdc6/) might be useful, specifically the `apt-get` commands? Although one difference would be using `gcc-9.4` instead of `gcc-4.9`.

**Comment by TheGuyWhoo** [comment]
Is it worth upgrading my gcc if I'm using a prebuilt binary? I didn't build it, I got it from releases page I think. Just making sure.

**Comment by TheGuyWhoo** [comment]
My gcc is 9.4.0. The issue still persists.

**Comment by TheGuyWhoo** [comment]
My libstdc++6 is also newest.

**Comment by jatinchowdhury18** [comment]
Hmm, interesting. I wonder if you plugin host is loading a different libstdc++ than the one installed on your system. Would you mind trying the steps from this [Stack Overflow](https://stackoverflow.com/a/75278570) answer.

**Comment by TheGuyWhoo** [comment]
Wait, conda is a requirement? It appears I don't even have it installed. Could that be the problem?

**Comment by TheGuyWhoo** [comment]
All of a sudden I could upgrade my libstd. Not sure what changed, I didn't do anything differently, but it's fixed now.

**Comment by jatinchowdhury18** [comment]
> Wait, conda is a requirement? It appears I don't even have it installed. Could that be the problem?

Ah sorry, I should have clarified... I meant inspecting the `libstdc++.so` file, as shown in that Stack Overflow answer.

> All of a sudden I could upgrade my libstd. Not sure what changed, I didn't do anything differently, but it's fixed now.

Okay! I guess it's good that it's working... maybe someday I'll understand the situation a bit better. Thanks for your patience!

**Comment by TheGuyWhoo** [comment]
I think I may have added a new repo at some point after the initial test that allowed me to upgrade. All the same, thanks!
